### ISSUE TITLE
FR8. Anonymous User Option

### ISSUE THREAD

**Issue by burahaun** [WSU-4110/CareConnect#16]
|FR8. Anonymous User Option|
|---|
|**Goal**: Allow registered users to enable the "Anonymous User Option," which lets them interact with the platform while keeping their profiles anonymous.
**Stakeholders:** Registered users, platform administrators|
| **Description:** Registered users can choose to enable the "Anonymous User Option" within their profile settings. When this option is activated, their interactions, such as comments, posts, or messages, will be displayed on the platform without revealing their real identity or personal information. Instead, a pseudonym or alias provided by the user will be used to identify them. |
| **Origin:** The idea for this feature was suggested during user feedback sessions, where users expressed a desire for increased privacy and anonymity when using the platform.|
| **Version:** 1.0  |  
|**Date:** 10/19/2023  
|  **Priority:** 2 |

**Comment by Prangon108** [comment]
Given the constraints of a college project, implementing the "Anonymous User Option" (FR8) was not feasible due to the complexities involved in ensuring robust anonymity and privacy features while maintaining platform integrity. The tight project timeline and academic environment limited our ability to develop and thoroughly test such a sophisticated feature.
